### PR TITLE
Update land log

### PR DESCRIPTION
**Pull request by csweetapple**

### CODE REVIEW

**Review by BHFock — APPROVED** [review]

**Review by BHFock — CHANGES_REQUESTED** [review]
Please format as

YYYY-MM-DD ;   ????	; Name

Thanks

**Comment by csweetapple** [comment]
I've sorted the date format out. Not sure why it's showing a conflict... did you fix my previous lot of dates? Perhaps I didn't merge your changes before making any more.

**Comment by BHFock** [comment]
> I've sorted the date format out. Not sure why it's showing a conflict... did you fix my previous lot of dates? Perhaps I didn't merge your changes before making any more.

Hmm. I changed the format once I noticed that it broke the IO. 

https://github.com/BHFock/virtual-rowing-tour/commit/986be6d9dd115b1dcf3d2a161f5f3042130249e4

Thanks for the your script and the data update. I can have a look tonight, as I am also half way through a local branch to add the option for more than one team on the map.

**Comment by BHFock** [comment]
pull land log

**Pull request merged**
